# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "267d6605e7f818a948d07952090138a1"
application_url = "https://ix-moss-sie-environmental.trycloudflare.com"
embedded = true
name = "haroon_qr_app"
handle = "haroon_qr_app"

[build]
include_config_on_deploy = true
dev_store_url = "haroon-test2.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ix-moss-sie-environmental.trycloudflare.com/auth/callback",
  "https://ix-moss-sie-environmental.trycloudflare.com/auth/shopify/callback",
  "https://ix-moss-sie-environmental.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
